services:
  mysql:
    image: mysql:8-oracle
    restart: unless-stopped
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--socket=/tmp/mysql.sock']
    environment:
      - MYSQL_ROOT_PASSWORD=cae_root_pw
      - MYSQL_HOST=instructor_tools_mysql
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=canvas_app_explorer_local
      - MYSQL_USER=cae_user
      - MYSQL_PASSWORD=cae_pw
    ports:
      - "6306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro
    container_name: instructor_tools_mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
        RUN_FRONTEND: true
    volumes:
      # Mount only the needed directories for local development
      - ./frontend/app:/code/frontend/app
      - ./backend:/code/backend
    ports:
      - "5000:5000"
      - "5020:5020"
    container_name: instructor_tools
    env_file:
      - .env
    environment:
      - DEBUG=True
      - RUN_FRONTEND=true
      - RUN_QWORKER_DEV_MODE=true

  redis:
    image: redis:7
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "--include /usr/local/etc/redis/redis.conf" ]
